adobe/aem-uix-examples

content-fragment-language-copies-management/jest.setup.js, content-fragment-language-copies-management/src/actions/get-translations/index.js, content-fragment-language-copies-management/src/actions/quick-publish-translations/index.js, content-fragment-language-copies-management/src/actions/translations.js, content-fragment-language-copies-management/src/actions/unpublish-translations/index.js, content-fragment-language-copies-management/src/actions/utils.js, content-fragment-language-copies-management/src/test/get-translations.test.js, content-fragment-language-copies-management/src/test/quick-publish-translations.test.js, content-fragment-language-copies-management/src/test/unpublish-translations.test.js, content-fragment-language-copies-management/src/test/utils.test.js, content-fragment-language-copies-management/src/web-src/index.html, content-fragment-language-copies-management/src/web-src/src/components/App.js, content-fragment-language-copies-management/src/web-src/src/components/CFAdminConsoleExtensionRegistration.js, content-fragment-language-copies-management/src/web-src/src/components/CFEditorExtensionRegistration.js, content-fragment-language-copies-management/src/web-src/src/components/Constants.js, content-fragment-language-copies-management/src/web-src/src/components/ManageTranslationsModal.js, content-fragment-language-copies-management/src/web-src/src/components/Spinner.js, content-fragment-language-copies-management/src/web-src/src/components/Status.js, content-fragment-language-copies-management/src/web-src/src/exc-runtime.js, content-fragment-language-copies-management/src/web-src/src/index.css, content-fragment-language-copies-management/src/web-src/src/index.js, content-fragment-language-copies-management/src/web-src/src/utils.js
=> Updated license headers of "content-fragment-language-copies-management"

content-fragment-language-copies-management/src/web-src/src/components/CFEditorExtensionRegistration.js
=> CF Translations Management: changed cf-editor button type

cf-editor-form-field-customization-sample/src/aem-cf-editor-1/web-src/src/components/CustomizedField.css, cf-editor-form-field-customization-sample/src/aem-cf-editor-1/web-src/src/components/CustomizedField.js
Simplify the use case to do the word count.
Validation is available OOB.
=> SITES-17926: Implement "Custom Field" extensions for CF editor

content-fragment-simple-export/.babelrc, content-fragment-simple-export/.eslintignore, content-fragment-simple-export/.eslintrc.json, content-fragment-simple-export/.github/workflows/deploy_prod.yml, content-fragment-simple-export/.github/workflows/deploy_stage.yml, content-fragment-simple-export/.github/workflows/pr_test.yml, content-fragment-simple-export/.gitignore, content-fragment-simple-export/README.md, content-fragment-simple-export/app.config.yaml, content-fragment-simple-export/extension-manifest.json, content-fragment-simple-export/jest.setup.js, content-fragment-simple-export/package-lock.json, content-fragment-simple-export/package.json, content-fragment-simple-export/src/aem-cf-console-admin-1/actions/content-fragments.js, content-fragment-simple-export/src/aem-cf-console-admin-1/actions/export-content-fragments/index.js, content-fragment-simple-export/src/aem-cf-console-admin-1/actions/filters.js, content-fragment-simple-export/src/aem-cf-console-admin-1/actions/utils.js, content-fragment-simple-export/src/aem-cf-console-admin-1/ext.config.yaml, content-fragment-simple-export/src/aem-cf-console-admin-1/web-src/index.html, content-fragment-simple-export/src/aem-cf-console-admin-1/web-src/src/components/App.js, content-fragment-simple-export/src/aem-cf-console-admin-1/web-src/src/components/Constants.js, content-fragment-simple-export/src/aem-cf-console-admin-1/web-src/src/components/ExtensionRegistration.js, content-fragment-simple-export/src/aem-cf-console-admin-1/web-src/src/exc-runtime.js, content-fragment-simple-export/src/aem-cf-console-admin-1/web-src/src/index.css, content-fragment-simple-export/src/aem-cf-console-admin-1/web-src/src/index.js, content-fragment-simple-export/src/aem-cf-console-admin-1/web-src/src/utils.js
https://jira.corp.adobe.com/browse/SITES-16921
Customer case (Vodafone):
The customer wants to implement an extension that will export CFs according to applied criteria in Excel format (less desirable alternative CSV).
=> feat (SITES-16921): Added example of Content Fragment simple export

address-autocomplete/.babelrc, address-autocomplete/.eslintignore, address-autocomplete/.eslintrc.json, address-autocomplete/.github/workflows/deploy_prod.yml, address-autocomplete/.github/workflows/deploy_stage.yml, address-autocomplete/.github/workflows/pr_test.yml, address-autocomplete/.gitignore, address-autocomplete/README.md, address-autocomplete/app.config.yaml, address-autocomplete/extension-manifest.json, address-autocomplete/jest.setup.js, address-autocomplete/package-lock.json, address-autocomplete/package.json, address-autocomplete/src/aem-cf-editor-1/ext.config.yaml, address-autocomplete/src/aem-cf-editor-1/web-src/index.html, address-autocomplete/src/aem-cf-editor-1/web-src/src/components/AddressAutocompleteField.js, address-autocomplete/src/aem-cf-editor-1/web-src/src/components/App.js, address-autocomplete/src/aem-cf-editor-1/web-src/src/components/Constants.js, address-autocomplete/src/aem-cf-editor-1/web-src/src/components/ExtensionRegistration.js, address-autocomplete/src/aem-cf-editor-1/web-src/src/components/Spinner.js, address-autocomplete/src/aem-cf-editor-1/web-src/src/exc-runtime.js, address-autocomplete/src/aem-cf-editor-1/web-src/src/google-places.js, address-autocomplete/src/aem-cf-editor-1/web-src/src/index.css, address-autocomplete/src/aem-cf-editor-1/web-src/src/index.js, address-autocomplete/src/aem-cf-editor-1/web-src/src/utils.js, address-autocomplete/src/aem-cf-editor-1/web-src/src/web-config.js
https://jira.corp.adobe.com/browse/SITES-16080
=> feat(SITES-16080): US Address Autocomplete Custom Element

universal-editor-task-management/src/universal-editor-task-management/web-src/src/components/ExtensionRegistration.js
=> SITES-20664: passing configurations variables to MFE

cf-editor-form-field-dropdown-sample/src/aem-cf-editor-1/actions/dropdown-data/index.js, cf-editor-form-field-dropdown-sample/src/aem-cf-editor-1/web-src/src/components/Dropdown.js, cf-editor-form-field-dropdown-sample/src/aem-cf-editor-1/web-src/src/components/ExtensionRegistration.js, cf-editor-form-field-dropdown-sample/src/aem-cf-editor-1/web-src/src/utils.js
=> Sample extension

README.md
Update README.md with quickstart instructions.
The samples can be easily used by running `aio app init --repo adobe/aem-uix-examples/{example-folder}` command.
=> Update README.md with quickstart instructions

cf-editor-generate-variations/src/aem-cf-editor-1/web-src/src/components/ExtensionRegistration.js
https://jira.corp.adobe.com/browse/SITES-21521
[](https://jira.corp.adobe.com/browse/SITES-21521)
Change icon in UIX and in the generate variation button
=> SITES-21521: Update icon in app and UIX extensions

cf-console-header-menu-button-sample/package-lock.json, cf-console-header-menu-button-sample/package.json
Update aem-uix-examples-cf-console-header-menu-button to @adobe/uix-guest@^0.10.2
=> Update aem-uix-examples-cf-console-header-menu-button to @adobe/uix-guest@^0.10.2

cf-editor-form-field-dropdown-sample/src/aem-cf-editor-1/web-src/src/components/Dropdown.css, cf-editor-form-field-dropdown-sample/src/aem-cf-editor-1/web-src/src/components/Dropdown.js, cf-editor-form-field-dropdown-sample/src/aem-cf-editor-1/web-src/src/components/ExtensionRegistration.js
=> Cf editor form field dropdown sample

content-fragment-export-to-target/package-lock.json, content-fragment-export-to-target/package.json
=> - up libraries version

content-fragment-language-copies-management/_dot.env, content-fragment-language-copies-management/src/actions/translations.js
A fix that includes code corrections and updates the URLs to the AEM instance.
=> fix: Updated AEM instance URLs

cf-console-action-bar-button-sample/README.md
=> Commit to test build trigger

cf-console-all-points/.babelrc, cf-console-all-points/.eslintrc.json, cf-console-all-points/.github/workflows/deploy_prod.yml, cf-console-all-points/.github/workflows/deploy_stage.yml, cf-console-all-points/.github/workflows/pr_test.yml, cf-console-all-points/.gitignore, cf-console-all-points/README.md, cf-console-all-points/app.config.yaml, cf-console-all-points/extension-manifest.json, cf-console-all-points/hooks/post-deploy.js, cf-console-all-points/jest.setup.js, cf-console-all-points/package-lock.json, cf-console-all-points/package.json, cf-console-all-points/src/aem-cf-console-admin-1/ext.config.yaml, cf-console-all-points/src/aem-cf-console-admin-1/web-src/index.html, cf-console-all-points/src/aem-cf-console-admin-1/web-src/src/components/App.js, cf-console-all-points/src/aem-cf-console-admin-1/web-src/src/components/Constants.js, cf-console-all-points/src/aem-cf-console-admin-1/web-src/src/components/CustomActionButtonModal.js, cf-console-all-points/src/aem-cf-console-admin-1/web-src/src/components/CustomHeaderButtonModal.js, cf-console-all-points/src/aem-cf-console-admin-1/web-src/src/components/ExtensionRegistration.js, cf-console-all-points/src/aem-cf-console-admin-1/web-src/src/index.css, cf-console-all-points/src/aem-cf-console-admin-1/web-src/src/index.js, cf-console-all-points/src/aem-cf-console-admin-1/web-src/src/utils.js
Related to this JIRA: https://jira.corp.adobe.com/browse/SITES-24055
An extension with different extension points examples for CF Console. This extension could be used to do manual and automated tests. More details of tested cases in this [Wiki](https://wiki.corp.adobe.com/display/dxdevx/Extensible+Services+Test+Cases)
=> SITES-24055 Add CF Console test extension all points

cf-editor-custom-rte-field/.babelrc, cf-editor-custom-rte-field/.gitignore, cf-editor-custom-rte-field/README.md, cf-editor-custom-rte-field/app.config.yaml, cf-editor-custom-rte-field/hooks/post-deploy.js, cf-editor-custom-rte-field/jest.setup.js, cf-editor-custom-rte-field/package-lock.json, cf-editor-custom-rte-field/package.json, cf-editor-custom-rte-field/patches/README.md, cf-editor-custom-rte-field/patches/tinymce/plugins/link/index.js, cf-editor-custom-rte-field/patches/tinymce/plugins/link/plugin.js, cf-editor-custom-rte-field/patches/tinymce6.8.2_link_plugin.patch, cf-editor-custom-rte-field/src/aem-cf-editor-1/ext.config.yaml, cf-editor-custom-rte-field/src/aem-cf-editor-1/web-src/index.html, cf-editor-custom-rte-field/src/aem-cf-editor-1/web-src/src/components/App.js, cf-editor-custom-rte-field/src/aem-cf-editor-1/web-src/src/components/Constants.js, cf-editor-custom-rte-field/src/aem-cf-editor-1/web-src/src/components/CustomTinymceField.js, cf-editor-custom-rte-field/src/aem-cf-editor-1/web-src/src/components/ExtensionRegistration.js, cf-editor-custom-rte-field/src/aem-cf-editor-1/web-src/src/index.css, cf-editor-custom-rte-field/src/aem-cf-editor-1/web-src/src/index.js
=> cf-editor-custom-rte-field

content-fragment-language-copies-management/README.md, content-fragment-language-copies-management/_dot.env, content-fragment-language-copies-management/app.config.yaml, content-fragment-language-copies-management/src/actions/translations.js
Wrong endpoint was specified in env variable. Moved endpoint path to the code in order to avoid such issues in the future
=> Fixed wrong translation endpoint for translation extension

README.md, aem-contenthub-assets-details-sample/.babelrc, aem-contenthub-assets-details-sample/.eslintrc.json, aem-contenthub-assets-details-sample/.github/workflows/deploy_prod.yml, aem-contenthub-assets-details-sample/.github/workflows/deploy_stage.yml, aem-contenthub-assets-details-sample/.github/workflows/pr_test.yml, aem-contenthub-assets-details-sample/.gitignore, aem-contenthub-assets-details-sample/README.md, aem-contenthub-assets-details-sample/app.config.yaml, aem-contenthub-assets-details-sample/extension-manifest.json, aem-contenthub-assets-details-sample/hooks/post-deploy.js, aem-contenthub-assets-details-sample/jest.setup.js, aem-contenthub-assets-details-sample/package-lock.json, aem-contenthub-assets-details-sample/package.json, aem-contenthub-assets-details-sample/src/aem-contenthub-assets-details-1/actions/generic/index.js, aem-contenthub-assets-details-sample/src/aem-contenthub-assets-details-1/actions/utils.js, aem-contenthub-assets-details-sample/src/aem-contenthub-assets-details-1/e2e/generic.e2e.test.js, aem-contenthub-assets-details-sample/src/aem-contenthub-assets-details-1/ext.config.yaml, aem-contenthub-assets-details-sample/src/aem-contenthub-assets-details-1/test/utils.test.js, aem-contenthub-assets-details-sample/src/aem-contenthub-assets-details-1/web-src/index.html, aem-contenthub-assets-details-sample/src/aem-contenthub-assets-details-1/web-src/src/components/App.js, aem-contenthub-assets-details-sample/src/aem-contenthub-assets-details-1/web-src/src/components/Constants.js, aem-contenthub-assets-details-sample/src/aem-contenthub-assets-details-1/web-src/src/components/ExtensionRegistration.js, aem-contenthub-assets-details-sample/src/aem-contenthub-assets-details-1/web-src/src/components/PanelAssetDetailsExtensionTab.js, aem-contenthub-assets-details-sample/src/aem-contenthub-assets-details-1/web-src/src/index.css, aem-contenthub-assets-details-sample/src/aem-contenthub-assets-details-1/web-src/src/index.js, aem-contenthub-assets-details-sample/src/aem-contenthub-assets-details-1/web-src/src/utils.js
AEM Content Hub Asset Details Extension Sample App
This is a sample app example of AEM Content Hub Asset Details Extension
=> AEM Content Hub Asset Details Extension Sample App

cf-editor-form-field-dropdown-sample/src/aem-cf-editor-1/web-src/src/components/Dropdown.js
=> change setHeight into setStyles

cf-editor-custom-rte-field-like-original/.babelrc, cf-editor-custom-rte-field-like-original/.gitignore, cf-editor-custom-rte-field-like-original/README.md, cf-editor-custom-rte-field-like-original/app.config.yaml, cf-editor-custom-rte-field-like-original/hooks/post-deploy.js, cf-editor-custom-rte-field-like-original/jest.setup.js, cf-editor-custom-rte-field-like-original/package-lock.json, cf-editor-custom-rte-field-like-original/package.json, cf-editor-custom-rte-field-like-original/patches/README.md, cf-editor-custom-rte-field-like-original/patches/tinymce/plugins/link/index.js, cf-editor-custom-rte-field-like-original/patches/tinymce/plugins/link/plugin.js, cf-editor-custom-rte-field-like-original/patches/tinymce6.8.2_link_plugin.patch, cf-editor-custom-rte-field-like-original/src/aem-cf-editor-1/ext.config.yaml, cf-editor-custom-rte-field-like-original/src/aem-cf-editor-1/web-src/index.html, cf-editor-custom-rte-field-like-original/src/aem-cf-editor-1/web-src/src/components/App.js, cf-editor-custom-rte-field-like-original/src/aem-cf-editor-1/web-src/src/components/Constants.js, cf-editor-custom-rte-field-like-original/src/aem-cf-editor-1/web-src/src/components/CustomTinymceField.js, cf-editor-custom-rte-field-like-original/src/aem-cf-editor-1/web-src/src/components/ExtensionRegistration.js, cf-editor-custom-rte-field-like-original/src/aem-cf-editor-1/web-src/src/components/rte.css, cf-editor-custom-rte-field-like-original/src/aem-cf-editor-1/web-src/src/index.css, cf-editor-custom-rte-field-like-original/src/aem-cf-editor-1/web-src/src/index.js
=> add example extention with RTE

cf-editor-custom-rte-field-like-original/src/aem-cf-editor-1/web-src/src/components/CustomTinymceField.js, cf-editor-custom-rte-field-like-original/src/aem-cf-editor-1/web-src/src/index.css
=> update spacings and iframe init
